import nextra from "nextra";

// The site is a Nextra 4 docs app over `content/`. Almost all of that
// directory is generated by the exporter in the private storefront
// repository and committed here as an ordinary diff — see CONTRIBUTING.md.
const withNextra = nextra({
  defaultShowCopyCode: true,
});

export default withNextra({
  reactStrictMode: true,
  // No rewrites, no redirects, no env: this app reads its own repository
  // and nothing else. It holds no credential and has no network dependency
  // at build time or at request time.
});
